# This file contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT License"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[${forgeMinVersion},)" #mandatory (28 is current forge version)

# A URL to refer people to when problems occur with this mod
issueTrackerURL="${modTrackerUrl}" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="${modId}" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory

# A display name for the mod
displayName="${modName}" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="${modUrl}" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="Prometheus_Exporter.png" #optional

# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional

# A text field displayed in the mod UI
authors="${modAuthors}" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
This mod provides a Prometheus exporter for Minecraft. It exports metrics related to the Minecraft server and the JVM for consumption by the open-source systems monitoring toolkit, Prometheus. The mod is intended for server-side use, and does not need to be installed client-side.
'''

# Forge dependency.
[[dependencies.${modId}]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[${forgeMinVersion},)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="SERVER"

# Minecraft dependency.
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftMinVersion},)"
    ordering="NONE"
    side="SERVER"
